#!/usr/bin/env bash
# Cross-compile single-file tagent binaries for every supported platform.
#
# Each binary embeds the agent (TUI + daemon + RPC), the 40-provider catalog
# and the full pre-built web GUI — download, run, done. No runtime, no install.
#
# Usage: scripts/build-binaries.sh [version] [target-filter]
#   version        default: read from version.ts
#   target-filter  optional substring filter, e.g. "windows x64" or "linux"
# Output: dist/tagent-v<version>/tagent-v<version>-<os>-<arch>[.exe] + SHA256SUMS.txt
#
# Small-RAM machines (v0.31.1): `bun build --compile` peaks at a few GB per
# target — on an 8 GB laptop with a browser open that is an OOM. When free
# RAM is low the build automatically runs bun with --smol (smaller heap at a
# small speed cost). Override: TAGENT_BUILD_SMOL=1 forces it on, =0 forces it
# off. Building just ONE target ("linux x64") also cuts the peak — each
# target is compiled separately and sequentially.
set -euo pipefail
cd "$(dirname "$0")/.."

VERSION="${1:-$(grep -oP "(?<=CURRENT_VERSION = ')[0-9][0-9a-zA-Z.]*" packages/core/src/version.ts)}"
FILTER="${2:-}"
if [ -z "${VERSION:-}" ]; then echo "[build] cannot determine version" >&2; exit 1; fi

OUT="dist/tagent-v$VERSION"
ENTRY="packages/cli/src/index.ts"
GEN="packages/cli/src/generated/gui-bundle.ts"

echo "[build] tagent v$VERSION → $OUT"

# ---------------------------------------------------------------- embed GUI --
# Fill packages/cli/src/generated/gui-bundle.ts with the base64 contents of
# gui-dist/, so `bun build --compile` bakes the web GUI into the executable.
python3 - gui-dist "$GEN" <<'PYEOF'
import base64, json, os, sys

src, out = sys.argv[1], sys.argv[2]
files = {}
for root, dirs, names in os.walk(src):
    dirs[:] = sorted(d for d in dirs if not d.startswith('.'))
    for n in sorted(names):
        p = os.path.join(root, n)
        rel = os.path.relpath(p, src).replace(os.sep, '/')
        with open(p, 'rb') as f:
            files[rel] = base64.b64encode(f.read()).decode()

total = sum(len(v) for v in files.values())
header = """/**
 * Embedded web-GUI bundle - AUTO-GENERATED by scripts/build-binaries.sh, do not edit.
 * Source: gui-dist/ (%d files). Extracted at runtime to ~/.tagent/gui-cache/.
 */
""" % len(files)
with open(out, 'w') as f:
    f.write(header)
    f.write('export const GUI_BUNDLE_FILES: Record<string, string> = ')
    f.write(json.dumps(files, separators=(',', ':')))
    f.write('\n')
print(f"[build] embedded {len(files)} GUI files ({total:,} base64 chars) into {out}")
PYEOF

# The generated file must never land in a commit - restore the committed stub.
restore_stub() {
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    git checkout -- "$GEN" 2>/dev/null || true
  fi
  if ! grep -q 'intentionally empty' "$GEN" 2>/dev/null; then
    cat > "$GEN" <<'STUB'
/**
 * Embedded web-GUI bundle — AUTO-GENERATED, do not edit by hand.
 *
 * This committed stub is intentionally empty: when running from source the
 * GUI is served straight from the repo's gui-dist/ folder. Before each
 * `bun build --compile`, scripts/build-binaries.sh fills this file with the
 * base64 contents of gui-dist/ (and restores the stub afterwards), so the
 * single-file binaries ship the full web GUI inside the executable. On first
 * run it self-extracts to ~/.tagent/gui-cache/<digest>/.
 */
export const GUI_BUNDLE_FILES: Record<string, string> = {}
STUB
  fi
}
trap restore_stub EXIT

# ------------------------------------------------------------------ targets --
# os-name  arch   (bun appends .exe to windows targets automatically)
TARGETS=(
  "windows x64"
  "windows arm64"
  "linux x64"
  "linux arm64"
  "macos x64"
  "macos arm64"
)

mkdir -p "$OUT"

# -------------------------------------------------- small-RAM build mode --
# free RAM (MB): linux /proc/meminfo · darwin page-stats · else unlimited
free_ram_mb() {
  if [ -r /proc/meminfo ]; then
    awk '/^MemAvailable:/ {print int($2/1024); exit}' /proc/meminfo
  elif command -v vm_stat >/dev/null 2>&1; then
    # darwin: free + speculative pages (best effort)
    local pages ps
    pages=$(vm_stat | awk '/Pages free/ {gsub("\.",""); print $3}')
    ps=$(vm_stat | awk '/Pages speculative/ {gsub("\.",""); print $3}')
    echo $(( (pages + ps) * 4096 / 1048576 ))
  else
    echo 999999
  fi
}
SMOL=""
if [ "${TAGENT_BUILD_SMOL:-}" = "1" ]; then
  SMOL="--smol"
  echo "[build] TAGENT_BUILD_SMOL=1 → bun --smol (forced)"
elif [ "${TAGENT_BUILD_SMOL:-}" = "0" ]; then
  echo "[build] TAGENT_BUILD_SMOL=0 → full heap (forced)"
else
  AVAIL=$(free_ram_mb)
  if [ "$AVAIL" -lt 6144 ]; then
    SMOL="--smol"
    echo "[build] free RAM ${AVAIL}MB < 6GB → bun --smol (smaller heap; TAGENT_BUILD_SMOL=0 to force off)"
  fi
fi

BUILT=0
for t in "${TARGETS[@]}"; do
  if [ -n "$FILTER" ] && [[ "$t" != *"$FILTER"* ]]; then continue; fi
  read -r osname arch <<< "$t"
  case "$osname" in
    macos) bun_target="bun-darwin-$arch" ;;
    *)     bun_target="bun-$osname-$arch" ;;
  esac
  outfile="$OUT/tagent-v$VERSION-$osname-$arch"
  echo "[build] → $outfile"
  # playwright is optional (browser tool resolves it at runtime) - keep it out.
  # --smol is a RUNTIME flag (heap discipline) — it goes before the subcommand.
  # shellcheck disable=SC2086 — $SMOL is intentionally word-split when empty
  bun $SMOL build --compile --external playwright --target="$bun_target" "$ENTRY" --outfile "$outfile"
  BUILT=$((BUILT+1))
done

# --------------------------------------------------------------- checksums --
# only when the full set exists (or nothing was filtered)
EXPECTED=6
PRESENT=$(ls "$OUT"/tagent-v* 2>/dev/null | wc -l)
if [ "$PRESENT" -ge "$EXPECTED" ]; then
  (cd "$OUT" && sha256sum tagent-v* > SHA256SUMS.txt)
  echo "[build] checksums written"
fi
echo
echo "[build] done ($BUILT built this run, $PRESENT/$EXPECTED present):"
ls -lh "$OUT"
