import fs from 'node:fs'
import path from 'node:path'
import type { ToolDefinition } from '../types'
import { ensureDir } from '../util'

/**
 * Test-mode report writer — the ONLY file write test mode can do, and only to
 * fixed locations (TEST-REPORT.md at the workspace root + a timestamped copy
 * under .tagent/test/). This is the artifact the user keeps: verdict, feature
 * checklist, responsive findings, issues with evidence.
 */

const VERDICTS = new Set(['pass', 'warn', 'fail'])
const VERDICT_BADGE: Record<string, string> = {
  pass: '✅ PASS',
  warn: '⚠️ PASS WITH WARNINGS',
  fail: '❌ FAIL',
}

export const testReportTool: ToolDefinition = {
  name: 'test_report',
  description:
    'Write the final test report (test mode only). Call this ONCE at the end of the run with verdict ' +
    '(pass | warn | fail) and the full markdown report. Saves TEST-REPORT.md at the workspace root ' +
    'plus a timestamped copy in .tagent/test/ — then give the user a short inline summary.',
  risk: 'low',
  params: {
    verdict: 'string (required) — "pass" | "warn" | "fail"',
    markdown: 'string (required) — the full report body (feature checklist, issues, responsive findings, evidence)',
  },
  inputSchema: {
    type: 'object',
    properties: {
      verdict: { type: 'string', enum: ['pass', 'warn', 'fail'], description: 'Overall verdict' },
      markdown: { type: 'string', description: 'Full markdown report body' },
    },
    required: ['verdict', 'markdown'],
  },
  async run(input, ctx) {
    const verdict = String(input.verdict ?? '').toLowerCase()
    if (!VERDICTS.has(verdict)) return `Error: verdict must be pass | warn | fail (got "${input.verdict}")`
    const body = String(input.markdown ?? '').trim()
    if (!body) return 'Error: markdown body is required'

    const root = ctx.workspaceRoot
    const dir = path.join(root, '.tagent', 'test')
    ensureDir(dir)

    const header = [
      `<!-- generated by tagent test mode · ${new Date().toISOString()} -->`,
      `# Test Report — ${VERDICT_BADGE[verdict]}`,
      '',
      `- date: ${new Date().toISOString().slice(0, 16).replace('T', ' ')} UTC`,
      `- workspace: ${path.basename(root)}`,
      '',
    ].join('\n')
    const full = `${header}${body}\n`

    const main = path.join(root, 'TEST-REPORT.md')
    const history = path.join(dir, `report-${Date.now()}.md`)
    fs.writeFileSync(main, full)
    fs.writeFileSync(history, full)

    ctx.events.onNotify?.(
      verdict === 'fail' ? 'error' : verdict === 'warn' ? 'warn' : 'info',
      `test report saved — verdict: ${verdict.toUpperCase()}`,
    )
    return [
      `Report saved (${VERDICT_BADGE[verdict]}):`,
      `  ${path.relative(root, main)} (root) + ${path.relative(root, history)} (history)`,
      'Now reply to the user with a SHORT summary: verdict, top issues, where the report is.',
    ].join('\n')
  },
}
