import fs from 'node:fs'
import path from 'node:path'
import type { AgentMode, SessionData, SessionMeta } from './types'
import { ensureDir, uid } from './util'

/**
 * Session persistence — one JSON file per session under <root>/.tagent/sessions/.
 * Zero-dependency by design (SQLite upgrade is a drop-in later).
 *
 * Every session also keeps a TRANSCRIPT sidecar (<id>.transcript.json) — the
 * rendered chat text as the user read it (ANSI included). The messages in
 * the session file are the agent's memory; the sidecar is the TEXT, so
 * reopening tagent shows the previous chat and `/clear [count|all]` can wipe
 * the text without touching memory.
 */

/** one persisted transcript line — `m: 1` marks the first line of a chat
 *  message (user echo box / assistant reply), the unit /clear <count> trims. */
export interface TranscriptEntry {
  t: string
  m?: 1
}

const TRANSCRIPT_CAP = 4000

export class SessionStore {
  private dir: string
  /** sidecar cache — append-heavy: read once, keep in memory, rewrite */
  private tCache = new Map<string, TranscriptEntry[]>()
  /** high-water mark of emitted timestamps — see nextTs() */
  private lastTs = 0

  constructor(private root: string, private workspaceId: string) {
    this.dir = path.join(root, '.tagent', 'sessions')
    ensureDir(this.dir)
  }

  /** strictly-increasing wall clock per store. Sessions born in the same
   *  millisecond (scripted flows, fast /new) otherwise tie in list()'s sort
   *  and readdir order silently picks the boot-resume "newest" — the wrong
   *  chat can come back. Monotonic + never below the record it updates. */
  private nextTs(after?: number): number {
    const ts = Math.max(Date.now(), this.lastTs + 1, (after ?? 0) + 1)
    this.lastTs = ts
    return ts
  }

  private file(id: string): string {
    // ids are generated by uid() — sanitize anyway
    const safe = id.replace(/[^a-zA-Z0-9_-]/g, '')
    return path.join(this.dir, `${safe}.json`)
  }

  private transcriptFile(id: string): string {
    const safe = id.replace(/[^a-zA-Z0-9_-]/g, '')
    return path.join(this.dir, `${safe}.transcript.json`)
  }

  create(title: string, model: string, mode: AgentMode): SessionData {
    const born = this.nextTs()
    const session: SessionData = {
      id: uid(),
      workspaceId: this.workspaceId,
      title: title.slice(0, 80) || 'New session',
      model,
      mode,
      createdAt: born,
      updatedAt: born,
      messageCount: 0,
      messages: [],
      todos: [],
    }
    this.save(session)
    return session
  }

  save(session: SessionData): void {
    session.updatedAt = this.nextTs(session.updatedAt)
    session.messageCount = session.messages.length
    ensureDir(this.dir)
    fs.writeFileSync(this.file(session.id), JSON.stringify(session, null, 1))
  }

  load(id: string): SessionData | undefined {
    try {
      return JSON.parse(fs.readFileSync(this.file(id), 'utf8'))
    } catch {
      return undefined
    }
  }

  rename(id: string, title: string): SessionData | undefined {
    const s = this.load(id)
    if (!s) return undefined
    s.title = title.replace(/\s+/g, ' ').trim().slice(0, 80) || 'Untitled'
    this.save(s)
    return s
  }

  list(): SessionMeta[] {
    return this.readAll()
      .filter((s) => !s.subagent)
      // newest first — createdAt breaks updatedAt ties (sessions born in
      // the same millisecond)
      .sort((a, b) => b.updatedAt - a.updatedAt || b.createdAt - a.createdAt)
  }

  /** Subagent sessions of one parent, oldest first — the run timeline. */
  listSubagents(parentId: string): SessionMeta[] {
    return this.readAll()
      .filter((s) => s.subagent === true && s.parentId === parentId)
      .sort((a, b) => a.createdAt - b.createdAt)
  }

  private readAll(): SessionMeta[] {
    let entries: string[]
    try {
      entries = fs.readdirSync(this.dir)
    } catch {
      return []
    }
    const metas: SessionMeta[] = []
    for (const e of entries) {
      // sidecars (<id>.transcript.json) also end in .json — they are the
      // rendered text, never sessions
      if (!e.endsWith('.json') || e.endsWith('.transcript.json')) continue
      try {
        const s: SessionData = JSON.parse(fs.readFileSync(path.join(this.dir, e), 'utf8'))
        metas.push({
          id: s.id,
          workspaceId: s.workspaceId,
          title: s.title,
          model: s.model,
          mode: s.mode,
          createdAt: s.createdAt,
          updatedAt: s.updatedAt,
          messageCount: s.messageCount,
          parentId: s.parentId,
          subagent: s.subagent,
        })
      } catch { /* skip broken */ }
    }
    return metas
  }

  delete(id: string): void {
    this.tCache.delete(id)
    try { fs.unlinkSync(this.file(id)) } catch { /* noop */ }
    try { fs.unlinkSync(this.transcriptFile(id)) } catch { /* noop */ }
  }

  /* ---------------- transcript sidecar ---------------- */

  /** the persisted chat text — [] when the session never had any. */
  readTranscript(id: string): TranscriptEntry[] {
    const cached = this.tCache.get(id)
    if (cached) return cached
    let entries: TranscriptEntry[] = []
    try {
      const raw = JSON.parse(fs.readFileSync(this.transcriptFile(id), 'utf8')) as TranscriptEntry[]
      if (Array.isArray(raw)) {
        entries = raw.filter((e) => e && typeof e.t === 'string')
      }
    } catch {
      /* no sidecar yet */
    }
    this.tCache.set(id, entries)
    return entries
  }

  /** append lines to the sidecar (capped, best-effort — a read-only
   *  workspace loses nothing but the text restore). */
  appendTranscript(id: string, entries: TranscriptEntry[]): void {
    if (entries.length === 0) return
    const all = [...this.readTranscript(id), ...entries].slice(-TRANSCRIPT_CAP)
    this.tCache.set(id, all)
    try {
      ensureDir(this.dir)
      fs.writeFileSync(this.transcriptFile(id), JSON.stringify(all, null, 1))
    } catch {
      /* read-only — cache keeps this run consistent */
    }
  }

  /** keep only the first `keepFirst` entries — /clear <count>. 0 wipes. */
  trimTranscript(id: string, keepFirst: number): void {
    const all = this.readTranscript(id)
    if (keepFirst >= all.length) return
    const next = all.slice(0, Math.max(0, Math.floor(keepFirst)))
    this.tCache.set(id, next)
    try {
      ensureDir(this.dir)
      fs.writeFileSync(this.transcriptFile(id), JSON.stringify(next, null, 1))
    } catch {
      /* read-only */
    }
  }
}
