import fs from 'node:fs'
import path from 'node:path'
import type { AgentMode, SessionData, SessionMeta } from './types'
import { ensureDir, uid } from './util'

/**
 * Session persistence — one JSON file per session under <root>/.tagent/sessions/.
 * Zero-dependency by design (SQLite upgrade is a drop-in later).
 */
export class SessionStore {
  private dir: string

  constructor(private root: string, private workspaceId: string) {
    this.dir = path.join(root, '.tagent', 'sessions')
    ensureDir(this.dir)
  }

  private file(id: string): string {
    // ids are generated by uid() — sanitize anyway
    const safe = id.replace(/[^a-zA-Z0-9_-]/g, '')
    return path.join(this.dir, `${safe}.json`)
  }

  create(title: string, model: string, mode: AgentMode): SessionData {
    const session: SessionData = {
      id: uid(),
      workspaceId: this.workspaceId,
      title: title.slice(0, 80) || 'New session',
      model,
      mode,
      createdAt: Date.now(),
      updatedAt: Date.now(),
      messageCount: 0,
      messages: [],
      todos: [],
    }
    this.save(session)
    return session
  }

  save(session: SessionData): void {
    session.updatedAt = Date.now()
    session.messageCount = session.messages.length
    ensureDir(this.dir)
    fs.writeFileSync(this.file(session.id), JSON.stringify(session, null, 1))
  }

  load(id: string): SessionData | undefined {
    try {
      return JSON.parse(fs.readFileSync(this.file(id), 'utf8'))
    } catch {
      return undefined
    }
  }

  rename(id: string, title: string): SessionData | undefined {
    const s = this.load(id)
    if (!s) return undefined
    s.title = title.replace(/\s+/g, ' ').trim().slice(0, 80) || 'Untitled'
    this.save(s)
    return s
  }

  list(): SessionMeta[] {
    return this.readAll()
      .filter((s) => !s.subagent)
      .sort((a, b) => b.updatedAt - a.updatedAt)
  }

  /** Subagent sessions of one parent, oldest first — the run timeline. */
  listSubagents(parentId: string): SessionMeta[] {
    return this.readAll()
      .filter((s) => s.subagent === true && s.parentId === parentId)
      .sort((a, b) => a.createdAt - b.createdAt)
  }

  private readAll(): SessionMeta[] {
    let entries: string[]
    try {
      entries = fs.readdirSync(this.dir)
    } catch {
      return []
    }
    const metas: SessionMeta[] = []
    for (const e of entries) {
      if (!e.endsWith('.json')) continue
      try {
        const s: SessionData = JSON.parse(fs.readFileSync(path.join(this.dir, e), 'utf8'))
        metas.push({
          id: s.id,
          workspaceId: s.workspaceId,
          title: s.title,
          model: s.model,
          mode: s.mode,
          createdAt: s.createdAt,
          updatedAt: s.updatedAt,
          messageCount: s.messageCount,
          parentId: s.parentId,
          subagent: s.subagent,
        })
      } catch { /* skip broken */ }
    }
    return metas
  }

  delete(id: string): void {
    try { fs.unlinkSync(this.file(id)) } catch { /* noop */ }
  }
}
