#!/usr/bin/env bash
# Cross-compile single-file tagent binaries for every supported platform.
#
# Each binary embeds the agent (TUI + daemon + RPC), the 40-provider catalog
# and the full pre-built web GUI — download, run, done. No runtime, no install.
#
# Usage: scripts/build-binaries.sh [version]   (default: read from version.ts)
# Output: dist/tagent-v<version>/tagent-v<version>-<os>-<arch>[.exe] + SHA256SUMS.txt
set -euo pipefail
cd "$(dirname "$0")/.."

VERSION="${1:-$(grep -oP "(?<=CURRENT_VERSION = ')[0-9][0-9a-zA-Z.]*" packages/core/src/version.ts)}"
if [ -z "${VERSION:-}" ]; then echo "[build] cannot determine version" >&2; exit 1; fi

OUT="dist/tagent-v$VERSION"
ENTRY="packages/cli/src/index.ts"
GEN="packages/cli/src/generated/gui-bundle.ts"

echo "[build] tagent v$VERSION → $OUT"

# ---------------------------------------------------------------- embed GUI --
# Fill packages/cli/src/generated/gui-bundle.ts with the base64 contents of
# gui-dist/, so `bun build --compile` bakes the web GUI into the executable.
python3 - gui-dist "$GEN" <<'PYEOF'
import base64, json, os, sys

src, out = sys.argv[1], sys.argv[2]
files = {}
for root, dirs, names in os.walk(src):
    dirs[:] = sorted(d for d in dirs if not d.startswith('.'))
    for n in sorted(names):
        p = os.path.join(root, n)
        rel = os.path.relpath(p, src).replace(os.sep, '/')
        with open(p, 'rb') as f:
            files[rel] = base64.b64encode(f.read()).decode()

total = sum(len(v) for v in files.values())
header = """/**
 * Embedded web-GUI bundle - AUTO-GENERATED by scripts/build-binaries.sh, do not edit.
 * Source: gui-dist/ (%d files). Extracted at runtime to ~/.tagent/gui-cache/.
 */
""" % len(files)
with open(out, 'w') as f:
    f.write(header)
    f.write('export const GUI_BUNDLE_FILES: Record<string, string> = ')
    f.write(json.dumps(files, separators=(',', ':')))
    f.write('\n')
print(f"[build] embedded {len(files)} GUI files ({total:,} base64 chars) into {out}")
PYEOF

# The generated file must never land in a commit - restore the committed stub.
restore_stub() {
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    git checkout -- "$GEN" 2>/dev/null || true
  fi
  if ! grep -q 'intentionally empty' "$GEN" 2>/dev/null; then
    cat > "$GEN" <<'STUB'
/**
 * Embedded web-GUI bundle — AUTO-GENERATED, do not edit by hand.
 *
 * This committed stub is intentionally empty: when running from source the
 * GUI is served straight from the repo's gui-dist/ folder. Before each
 * `bun build --compile`, scripts/build-binaries.sh fills this file with the
 * base64 contents of gui-dist/ (and restores the stub afterwards), so the
 * single-file binaries ship the full web GUI inside the executable. On first
 * run it self-extracts to ~/.tagent/gui-cache/<digest>/.
 */
export const GUI_BUNDLE_FILES: Record<string, string> = {}
STUB
  fi
}
trap restore_stub EXIT

# ------------------------------------------------------------------ targets --
# os-name  arch   (bun appends .exe to windows targets automatically)
TARGETS=(
  "windows x64"
  "windows arm64"
  "linux x64"
  "linux arm64"
  "macos x64"
  "macos arm64"
)

mkdir -p "$OUT"
for t in "${TARGETS[@]}"; do
  read -r osname arch <<< "$t"
  case "$osname" in
    macos) bun_target="bun-darwin-$arch" ;;
    *)     bun_target="bun-$osname-$arch" ;;
  esac
  outfile="$OUT/tagent-v$VERSION-$osname-$arch"
  echo "[build] → $outfile"
  # playwright is optional (browser tool resolves it at runtime) - keep it out.
  bun build --compile --external playwright --target="$bun_target" "$ENTRY" --outfile "$outfile"
done

# --------------------------------------------------------------- checksums --
(cd "$OUT" && sha256sum tagent-v* > SHA256SUMS.txt)
echo
echo "[build] done:"
ls -lh "$OUT"
